# Generated by Django 4.0.4 on 2022-07-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do',
            name='completed',
            field=models.CharField(max_length=35),
        ),
    ]
